# Generated by Django 2.1.1 on 2018-11-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sosio',
            fields=[
                ('no', models.IntegerField(default=5, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField(default=5)),
                ('names', models.CharField(max_length=10)),
            ],
        ),
    ]
