# Generated by Django 2.1.1 on 2018-11-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosio',
            name='total',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='sosio',
            name='names',
            field=models.IntegerField(default=100),
        ),
    ]
