# Generated by Django 2.1.1 on 2018-11-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc1', '0004_auto_20181106_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosio',
            name='total',
        ),
    ]
